"use strict";
let num1;
let num2;
let result;
num1 = 10;
num2 = 5;
result = num1 + num2;
console.log("Result after addition:", result);
result = num1 - num2;
console.log("Result after subtraction:", result);
result = num1 * num2;
console.log("Result after multiplication:", result);
result = num1 / num2;
console.log("Result after division:", result);
result = num1 % num2;
console.log("Result after modulus:", result);
