"use strict";
let number1 = 10;
let number2 = 5;
let number3;
number3 = number1 + number2;
console.log("Result after addition:", number3);
number3 = number1 - number2;
console.log("Result after subtraction:", number3);
number3 = number1 * number2;
console.log("Result after multiplication:", number3);
number3 = number1 / number2;
console.log("Result after division:", number3);
number1 = "10";
number2 = true;
number3 = number1 + number2;
console.log("Result after addition with changed data types:", number3);
number3 = number1 - number2;
console.log("Result after subtraction with changed data types:", number3);
number3 = number1 * number2;
console.log("Result after multiplication with changed data types:", number3);
number3 = number1 / number2;
console.log("Result after division with changed data types:", number3);
